<?php
/**
 * Contacts Post Type
 *
 * This defines the Contacts custom post type. A majority of the DMM CRM app data
 * will be stored under this custom post type. Taxonomy and heavy use of meta
 * are used as well to construct the different data functionalities that this
 * plugin provides.
 * 
 * @package   DmmCrm
 * @author 	  Chasm Solutions <chasm.crew@chasm.solutions>
 * @link      https://github.com/ChasmSolutions
 * @copyright 2017 Chasm Solutions
 * @license   GPL-3.0
 * @version   0.0.1
 */

class Dmmcrm_Contacts_Post_Type
{
	/**
	 * Class Construct
	 */
	public function __construct() {
		add_action( 'init', array( $this, 'contacts_post_type' ), 0 );

	}

	/**
	 * Build the Contact Post Type
	 *
	 * WP REST API functionality has been added to the post type to allow JSON
	 * feeds of prayers. This allows you easily feed your data to other 3rd party
	 * apps that use JSON for processing data.
	 * 
	 * @return hook
	 * @since  0.9.0
	 */
	// Register Custom Post Type
	function contacts_post_type() {
	
		$labels = array(
			'name'                  => _x( 'Contacts', 'Post Type General Name', 'dmmcrm' ),
			'singular_name'         => _x( 'Contact', 'Post Type Singular Name', 'dmmcrm' ),
			'menu_name'             => __( 'Contacts', 'dmmcrm' ),
			'name_admin_bar'        => __( 'Contacts', 'dmmcrm' ),
			'archives'              => __( 'Contact Archives', 'dmmcrm' ),
			'attributes'            => __( 'Contact Attributes', 'dmmcrm' ),
			'parent_item_colon'     => __( 'Parent Contact:', 'dmmcrm' ),
			'all_items'             => __( 'All Contacts', 'dmmcrm' ),
			'add_new_item'          => __( 'Add New Contact', 'dmmcrm' ),
			'add_new'               => __( 'Add New', 'dmmcrm' ),
			'new_item'              => __( 'New Contact', 'dmmcrm' ),
			'edit_item'             => __( 'Edit Contact', 'dmmcrm' ),
			'update_item'           => __( 'Update Contact', 'dmmcrm' ),
			'view_item'             => __( 'View Contact', 'dmmcrm' ),
			'view_items'            => __( 'View Contacts', 'dmmcrm' ),
			'search_items'          => __( 'Search Contact', 'dmmcrm' ),
			'not_found'             => __( 'Not found', 'dmmcrm' ),
			'not_found_in_trash'    => __( 'Not found in Trash', 'dmmcrm' ),
			'featured_image'        => __( 'Featured Image', 'dmmcrm' ),
			'set_featured_image'    => __( 'Set featured image', 'dmmcrm' ),
			'remove_featured_image' => __( 'Remove featured image', 'dmmcrm' ),
			'use_featured_image'    => __( 'Use as featured image', 'dmmcrm' ),
			'insert_into_item'      => __( 'Insert into item', 'dmmcrm' ),
			'uploaded_to_this_item' => __( 'Uploaded to this item', 'dmmcrm' ),
			'items_list'            => __( 'Contacts list', 'dmmcrm' ),
			'items_list_navigation' => __( 'Contacts list navigation', 'dmmcrm' ),
			'filter_items_list'     => __( 'Filter contacts list', 'dmmcrm' ),
		);
		$rewrite = array(
			'slug'                  => 'contact',
			'with_front'            => true,
			'pages'                 => true,
			'feeds'                 => false,
		);
		$args = array(
			'label'                 => __( 'Contact', 'dmmcrm' ),
			'description'           => __( 'Contacts generated by the media to movement effort', 'dmmcrm' ),
			'labels'                => $labels,
			'supports'              => array( 'title', 'author', 'thumbnail', 'comments', 'revisions', 'custom-fields', ),
			'taxonomies'            => array( 'post_tag' ),
			'hierarchical'          => false,
			'public'                => true,
			'show_ui'               => true,
			'show_in_menu'          => true,
			'menu_position'         => 5,
			'menu_icon'             => 'dashicons-admin-users',
			'show_in_admin_bar'     => true,
			'show_in_nav_menus'     => true,
			'can_export'            => true,
			'has_archive'           => false,		
			'exclude_from_search'   => true,
			'publicly_queryable'    => false,
			'rewrite'               => $rewrite,
			'capability_type'       => 'post',
			'show_in_rest'          => true,
			'rest_base'             => 'contacts',
			'rest_controller_class' => 'WP_REST_Posts_Controller',
		);
		register_post_type( 'dmm_contacts', $args );
	
		}
}
